version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run: cargo build --release

  test:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run: cargo test

workflows:
  test:
    jobs:
      - test
      - build:
          requires:
            - test