//! Scene contains the data for the pre-made scenes that can be generated by this application.
//! They are all taken from the book "Raytracing in a Weekend"
pub mod checkered_spheres;
pub mod cornell_boxes;
pub mod earth;
pub mod final_scene;
pub mod perlin_spheres;
pub mod random_spheres;

use clap::ValueEnum;

/// `Scene` lists the available pre-made, default scenes that can be rendered
#[derive(Copy, Clone, Debug, Eq, PartialEq, ValueEnum)]
pub enum Scene {
    RandomSpheres = 1,
    PerlinSpheres = 2,
    Earth = 3,
    CornellBox = 4,
    CornellSmokeBoxes = 5,
    Final = 6,
}

impl Scene {
    /// Map in integer in 1..6 to a Scene
    pub fn map_to_scene(num: u32) -> Option<Scene> {
        match num {
            1 => Some(Scene::RandomSpheres),
            2 => Some(Scene::PerlinSpheres),
            3 => Some(Scene::Earth),
            4 => Some(Scene::CornellBox),
            5 => Some(Scene::CornellSmokeBoxes),
            6 => Some(Scene::Final),
            _ => None,
        }
    }
}
